controller_manager_ns: controller_manager
controller_list:
    - name: arm/arm_joint_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - base_to_armA
        - armA_to_armB
        - armB_to_armC
        - armC_to_armD
