arm:
    arm_joint_controller:
        type: "position_controllers/JointTrajectoryController"
        joints: 
            - base_to_armA
            - armA_to_armB
            - armB_to_armC
            - armC_to_armD
        
        gains:
            base_to_armA: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            armA_to_armB: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            armB_to_armC: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
            armC_to_armD: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    
    # 发布关节状态
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
